language: r
r:
  - release
  - devel
sudo: false
cache: packages

os:
  - linux
  - osx

r_github_packages:
  - jimhester/covr

after_success:
  - R CMD INSTALL $PKG_TARBALL
  - Rscript -e 'covr::codecov(type = "examples")'
