language: c
sudo: required

before_install:
  - curl -OL https://raw.githubusercontent.com/metacran/r-builder/master/pkg-build.sh
  - chmod 755 pkg-build.sh
  - ./pkg-build.sh bootstrap
  - sudo apt-get update -qq
  - sudo apt-get install -qq libgsl0-dev bwidget

install:
  - ./pkg-build.sh install_deps
  - ./pkg-build.sh install_github jimhester/covr yihui/knitr

script:
  - ./pkg-build.sh run_tests

after_failure:
  - ./pkg-build.sh dump_logs
  
after_success:
  - if [[ ! -z "$COVERAGE" ]];then ./pkg-build.sh run_script -e 'covr::codecov(type=Sys.getenv("COVERAGE"), quiet = FALSE)'; fi

notifications:
  email:
    on_success: change
    on_failure: change

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=false
  matrix:
    - RVERSION=release
    - RVERSION=devel COVERAGE=vignette R_CHECK_ARGS="--no-tests --no-build-vignettes --no-manual"
    - RVERSION=devel COVERAGE=test R_CHECK_ARGS="--no-tests --no-build-vignettes --no-manual"
    - RVERSION=devel COVERAGE=example R_CHECK_ARGS="--no-tests --no-build-vignettes --no-manual"
